### ISSUE TITLE
Question about sync signal

### ISSUE THREAD

**Issue by sonik-br** [benryves/XboxControllerAnalyser#1]
Hi Ben, thanks for this amazing tool. :)

I want to ask if you know more about the sync signal on the controller cable (for lightguns).
Would a ligntgun support an external composite video signal? (just like a ps2 guncon can)
I'm thinking on using a xbox light gun on a pc.

**Comment by benryves** [comment]
Sorry for the delayed response, I only just saw your message!

As far as I can tell the light guns require a composite sync signal, similar to the Guncon, however this signal is provided directly via the Xbox's controller port instead of needing an external pass-through cable. Without this signal the light gun controllers I've got either fail to report information properly, or simply fail to enumerate as USB devices entirely (presumably the on-board microcontroller is getting stuck trying to synchronise some timer to the missing video signal).

Unfortunately I'm not aware of any more specific details about this composite sync - such as voltage levels (I don't have access to an oscilloscope) or the specifications of what signals are supported (e.g. maximum resolution - as I have a PAL Xbox I've only been able to test at 15kHz). For my own testing I just had an Xbox console running in the background and used the composite sync signal from its controller ports, so that's four wires from the PC to the gun (+5V, D-, D+, GND) and two wires from the Xbox to the gun (CSYNC, GND). When I pointed the gun at the TV showing a picture being generated by the Xbox the joystick position changed on the PC as expected. Presumably you'd be able to tap off the composite sync from the VGA connector (if driving a VGA monitor and can enable composite sync, alternatively you might need a sync combiner) but you may also need to level shift this to a voltage the controller can handle - and that's not something I can test and answer for certain at this stage. Sorry I can't provide more concrete information about the electrical side!

**Comment by sonik-br** [comment]
Thank you for the reply.
I'm going to do some more research before trying to wire anything. Don't want to burn any device.
Closing but I will reply later if I get any success with it :)
